### ISSUE TITLE
Not working on swift 4.2

### ISSUE THREAD

**Issue by jnevesjunior** [philackm/ScrollableGraphView#149]
Hi, 

The ScrollableGraphView is not working on swift 4.2 and this is preventing me update my app to iOS 12

Thanks,
José

**Comment by jnevesjunior** [comment]
@philackm any updates?

**Comment by jnevesjunior** [comment]
I'll be forced to remove from my project, I can't wait more without any answer.
By

**Comment by elilabes** [comment]
This is also broken for me. @philackm

**Comment by philackm** [comment]
I will fix this tonight. 

For future reference, if someone has already fixed it and submitted a pull request (in this case it seems like a few people have), you can point directly to that commit in your cocoapod file without having to wait for me. (Be sure to switch it back when this repo has been updated however.) See: https://stackoverflow.com/questions/39261018/is-there-a-way-to-use-a-pull-request-with-cocoapods

**Comment by philackm** [comment]
This is now fixed. If you're using cocoapods, 4.0.6 should be available!

**Comment by jnevesjunior** [comment]
Thanks

**Comment by masterrr** [comment]
I believe this is not fixed for Carthage? 


`	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -project /Users/tk/Projects/Ketones/Carthage/Checkouts/ScrollableGraphView/carthage/ScrollableGraphView/ScrollableGraphView.xcodeproj -scheme ScrollableGraphView -configuration Release -derivedDataPath /Users/tk/Library/Caches/org.carthage.CarthageKit/DerivedData/10.0_10A255/ScrollableGraphView/4.0.6 -sdk iphoneos ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/61/z_ngk_rs3fq7zcdybcpd83rc0000gn/T/ScrollableGraphView SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/tk/Projects/Ketones/Carthage/Checkouts/ScrollableGraphView)`

Log: https://gist.github.com/masterrr/92e3e70682ce940ba926e15f81b817d5
